spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql://211.188.59.196:3306/cudo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mysql

  h2:
    console:
      enabled: false  # MySQL 사용 시 H2 콘솔은 비활성화하거나 그대로 둬도 무방

  defer-datasource-initialization: true


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.web.session: DEBUG
    org.springframework.web.filter.DelegatingFilterProxy: DEBUG